In [1]:
import numpy as np




In [2]:
a1d=np.array([1, 2, 3])


In [3]:
a1d


array([1, 2, 3])

In [4]:
type(np)

module

In [5]:
type(a1d)

numpy.ndarray

In [6]:
a2d=np.array([[1, 2, 3],[4, 5, 6]])

In [7]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
a3d=np.array([[[1.1,2,3],[4,5,6],[5,6,9]],[[1,2,3],[4,5,6],[5,6,9]]]) 

In [9]:
a3d

array([[[1.1, 2. , 3. ],
        [4. , 5. , 6. ],
        [5. , 6. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [5. , 6. , 9. ]]])

In [10]:
for block in a3d:
    print(block)
    print()  # Add space between blocks


[[1.1 2.  3. ]
 [4.  5.  6. ]
 [5.  6.  9. ]]

[[1. 2. 3.]
 [4. 5. 6.]
 [5. 6. 9.]]



In [11]:
for line in a3d:
    print(line)
    print()  # Add space between blocks


[[1.1 2.  3. ]
 [4.  5.  6. ]
 [5.  6.  9. ]]

[[1. 2. 3.]
 [4. 5. 6.]
 [5. 6. 9.]]



In [12]:
a2d.shape

(2, 3)

In [13]:
a1d.shape


(3,)

In [14]:
a3d.dtype

dtype('float64')

In [15]:
a3d.size

18

In [16]:
type(a3d)

numpy.ndarray

In [17]:
import pandas as pd

In [18]:
df = pd.DataFrame(a2d)

In [19]:
df

0  1  2
0  1  2  3
1  4  5  6

In [20]:
test_array=np.array([1,2,3])

In [21]:
test_array

array([1, 2, 3])

In [22]:
#ones
#zeros
#random
zeros=np.zeros([2,3])

In [23]:
zeros

array([[0., 0., 0.],
       [0., 0., 0.]])

In [24]:
type(zeros)

numpy.ndarray

In [25]:
range_array=np.arange(0,10,2)
#arage 3 properties (strat stop step)





In [26]:
range_array

array([0, 2, 4, 6, 8])

In [27]:
random_matrix=np.random.randint(0, 10, size=(3,5)) 

In [28]:
random_matrix

array([[3, 4, 5, 5, 6],
       [7, 2, 1, 6, 9],
       [7, 9, 0, 9, 0]], dtype=int32)

In [29]:
random_matrix.size

15

In [30]:
np.random.seed(seed=0)    #after putting seed no value will be changed..
rand_matrix=np.random.rand(3,5)  #auto range 0-1

In [31]:
rand_matrix

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318, 0.4236548 ],
       [0.64589411, 0.43758721, 0.891773  , 0.96366276, 0.38344152],
       [0.79172504, 0.52889492, 0.56804456, 0.92559664, 0.07103606]])

In [32]:
a3d


array([[[1.1, 2. , 3. ],
        [4. , 5. , 6. ],
        [5. , 6. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [5. , 6. , 9. ]]])

a1d


In [33]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [34]:
a3d

array([[[1.1, 2. , 3. ],
        [4. , 5. , 6. ],
        [5. , 6. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [5. , 6. , 9. ]]])

In [35]:
a2d[0]

array([1, 2, 3])

In [36]:
a2d[1]

array([4, 5, 6])

In [37]:
a3d

array([[[1.1, 2. , 3. ],
        [4. , 5. , 6. ],
        [5. , 6. , 9. ]],

       [[1. , 2. , 3. ],
        [4. , 5. , 6. ],
        [5. , 6. , 9. ]]])

In [38]:
a3d[0
]

array([[1.1, 2. , 3. ],
       [4. , 5. , 6. ],
       [5. , 6. , 9. ]])

In [39]:
a3d[1]

array([[1., 2., 3.],
       [4., 5., 6.],
       [5., 6., 9.]])

In [40]:
a3d[:2,:1]

array([[[1.1, 2. , 3. ]],

       [[1. , 2. , 3. ]]])

In [41]:
a3d[:2,:1,:2]

array([[[1.1, 2. ]],

       [[1. , 2. ]]])

In [42]:
arandom =np.random.randint(10, size=(2,3))   # creating a random matrixes with 3 column 2 rows

In [43]:
arandom

array([[9, 4, 3],
       [0, 3, 5]], dtype=int32)

In [44]:
arandom =np.random.randint(10, size=(3,3,3)) #create 3 column 3 rows 3 metrixes 

In [48]:
arandoma

NameError: name 'arandoma' is not defined

In [ ]:
arandom =np.random.randint(10, size=(3,4,5)) #create 5 column 4 rows 3 metrixes 

In [49]:
arandomarandom =np.random.randint(10, size=(3,4,5)) #create 5 column 4 rows 3 metrixes 

In [50]:
arandom =np.random.randint(10, size=(2,3,4,5)) #create 5 column 4 rows 3 metrixes and make whole one more so total will be a six matrixs

In [51]:
arandom 

array([[[[3, 4, 1, 2, 9],
         [1, 4, 6, 8, 2],
         [3, 0, 0, 6, 0],
         [6, 3, 3, 8, 8]],

        [[8, 2, 3, 2, 0],
         [8, 8, 3, 8, 2],
         [8, 4, 3, 0, 4],
         [3, 6, 9, 8, 0]],

        [[8, 5, 9, 0, 9],
         [6, 5, 3, 1, 8],
         [0, 4, 9, 6, 5],
         [7, 8, 8, 9, 2]]],


       [[[8, 6, 6, 9, 1],
         [6, 8, 8, 3, 2],
         [3, 6, 3, 6, 5],
         [7, 0, 8, 4, 6]],

        [[5, 8, 2, 3, 9],
         [7, 5, 3, 4, 5],
         [3, 3, 7, 9, 9],
         [9, 7, 3, 2, 3]],

        [[9, 7, 7, 5, 1],
         [2, 2, 8, 1, 5],
         [8, 4, 0, 2, 5],
         [5, 0, 8, 1, 1]]]], dtype=int32)

In [52]:
#array manipulation


In [53]:
a1d       #a1d manipulatee with ones 

array([1, 2, 3])

In [54]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
ones=np.ones([2,3])

In [56]:
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [57]:
a1d+ones   #it will add all elemant of a1d into theones array..

array([[2., 3., 4.],
       [2., 3., 4.]])

In [58]:
a2d/a1d

array([[1. , 1. , 1. ],
       [4. , 2.5, 2. ]])

In [59]:
a2d//a1d

array([[1, 1, 1],
       [4, 2, 2]])

In [60]:
a1d

array([1, 2, 3])

a1d**2

In [61]:
a1d **2

array([1, 4, 9])

In [63]:
a2d

array([[1, 2, 3],
       [4, 5, 6]])

In [64]:
a2d%2

array([[1, 0, 1],
       [0, 1, 0]])

In [65]:
### aggregation in numpy 

In [66]:
a1d

array([1, 2, 3])

In [67]:
sum(a1d)       #this iss python method :slower method 

np.int64(6)

In [68]:
np.sum(a1d)   #this is numpy method : faster

np.int64(6)

In [71]:
lambi_array=np.random.random(10000) #for finding 10000 elemnt 

In [73]:
lambi_array.size

10000

In [74]:
lambi_array[:20]

array([0.16469416, 0.6214784 , 0.57722859, 0.23789282, 0.934214  ,
       0.61396596, 0.5356328 , 0.58990998, 0.73012203, 0.311945  ,
       0.39822106, 0.20984375, 0.18619301, 0.94437239, 0.7395508 ,
       0.49045881, 0.22741463, 0.25435648, 0.05802916, 0.43441663])

In [ ]:
%timeit sum(lambi_array)
%timeit np.sum(lambi-array)        #for checking which one is more fast

In [77]:
np.max(a1d)

np.int64(3)

In [79]:
np.min(a1d)

np.int64(1)

In [81]:
#mean 
#std
#variance
np.mean(a1d)         #mean of a1d

np.float64(2.0)

In [83]:
np.var(a1d)    #variance of a1d

np.float64(0.6666666666666666)

In [90]:
np.sqrt(np.var(a1d))  #standard deviation manually  



np.float64(0.816496580927726)

In [91]:
np.std(a1d)    #built in function for finding standard deviation  

np.float64(0.816496580927726)